# Generated by Django 3.0.3 on 2020-06-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200629_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='img_pc',
            field=models.ImageField(default='', upload_to='images/pc/'),
        ),
        migrations.AddField(
            model_name='website',
            name='img_sm',
            field=models.ImageField(default='', upload_to='imges/sm/'),
        ),
    ]
