# Generated by Django 3.0.3 on 2020-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200701_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='img_pc',
            field=models.ImageField(default='', upload_to='images_pc'),
        ),
        migrations.AlterField(
            model_name='website',
            name='img_sm',
            field=models.ImageField(default='', upload_to='imges_sm'),
        ),
    ]
